apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-serve-metrics
  namespace: default
  labels:
    app: ray-serve
spec:
  selector:
    matchLabels:
      ray.io/serve: "true"
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
